
# DRS global configurations
global:

  # maimum allowed Secondary pairs with one Primary MSISDN
  pair_limit: 4

  # Length of pair-Code
  pc_length: 8

  # No of IMEIs per device
  imeis_per_device: 5

  # DataBase Parameters
  dbname: 'dps'
  dbusername: 'postgres'
  dbpassword: 'sms003'
  dbhost: '192.168.100.69'


  # SQL_ALCHEMY Parameters
  pool_size: 100
  pool_timeout: 20
  pool_recycle: 10
  overflow_size: 275

  # Operators related parameters
  CC: '92'
  MNO_1: 'jazz'
  MNO_2: 'telenor'
  MNO_3: 'ufone'
  MNO_4: 'zong'
  MNO_5: 'warid'

  # URLS
  kannel_sms: 'http://192.168.100.70:13013/cgi-bin/sendsms'

  # Pair-List generation Path
  pairlist_path: '/home/munawar/PycharmProjects/Device-Pairing-Subsystem/pairing_lists'

  # System Paths for files
  Download_Path: '/home/munawar/PycharmProjects/Device-Pairing-Subsystem/downloads'
  Upload_Path: '/home/munawar/PycharmProjects/Device-Pairing-Subsystem/uploads'

  # Multi-Language Support
  supported_languages:
    - es
    - en
    - id
  default_language: en

  regex:
    id: '^(?! )[A-Za-z\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s\x23\x2D\x40\x5F]{1,1000}(?<! )$'
    es: '^(?! )[A-Za-z\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s\x23\x2D\x40\x5F]{1,1000}(?<! )$'
    en: '^(?! )[A-Za-z\s\x23\x2D\x40\x5F]{1,1000}(?<! )$'

  # SMS Texts
  # Additional-Pair Messages
  sms_pair_limit_breached: 'Pairing limit breached: need to remove any existing pair'

